# In this file are the weights that assign importance to each feature of the offer.

rating_weights = {
    'offer_name': 1,
    'offer_thumbnail_url': 1,
    'price': 10,
    'street': 1,
    'district': 1,
    'date_of_the_offer': 8,
    'offer_id': 1,
    'furniture': 1,
    'area': 9,
    'price_per_m2': 9,
    'security_deposit': 2,
    'heating': 4,
    'building_year': 2,
    'fit_out': 1,

    'internet': 1,
    'cable_tv': 1,
    'closed_terrain': 1,
    'monitoring_or_security': 1,
    'entry_phone': 1,
    'antibulglar_doors_windows': 1,
    'alarm_system': 1,
    'antibulglar_blinds': 1,
    'dishwasher': 1,
    'cooker': 1,
    'fridge': 1,
    'oven': 1,
    'washing_machine': 1,
    'tv': 1,
    'elevator': 1,
    'phone': 1,
    'AC': 1,
    'garden': 1,
    'utility_room': 1,
    'parking_space': 1,
    'terrace': 1,
    'balcony': 1,
    'non_smokers_only': 1,
    'separate_kitchen': 1,
    'basement': 1,
    'virtual_walk': 1,
    'two_level_apartment': 1,
}