
offer_features = {
    'internet': 'internet',
    'dostępne od': 'ready_from',
    'telewizja kablowa': 'cable_tv',
    'teren zamknięty': 'closed_terrain',
    'monitoring / ochrona': 'monitoring_or_security',
    'monitoring': 'monitoring_or_security',
    'ochrona': 'monitoring_or_security',
    'osiedle strzeżone': 'monitoring_or_security',
    'domofon / wideofon': 'entry_phone',
    'domofon': 'entry_phone',
    'wideofon': 'entry_phone',
    'drzwi / okna antywłamaniowe': 'antibulglar_doors_windows',
    'drzwi antywłamaniowe': 'antibulglar_doors_windows',
    'okna antywłamaniowe': 'antibulglar_doors_windows',
    'system alarmowy': 'alarm_system',
    'alarm': 'alarm_system',
    'rolety antywłamaniowe': 'antibulglar_blinds',
    'zmywarka': 'dishwasher',
    'zmywarkę': 'dishwasher',
    'zmywarką': 'dishwasher',
    'kuchenka': 'cooker',
    'kuchenkę': 'cooker',
    'kuchenką': 'cooker',
    'lodówka': 'fridge',
    'lodówkę': 'fridge',
    'lodówką': 'fridge',
    'zamrażarkę': 'fridge',
    'zamrażarką': 'fridge',
    'piekarnik': 'oven',
    'pralka': 'washing_machine',
    'pralkę': 'washing_machine',
    'pralką': 'washing_machine',
    'telewizor': 'tv',
    'telewizj': 'tv',
    'winda': 'elevator',
    'windę': 'elevator',
    'windą': 'elevator',
    'telefon': 'phone',
    'klimatyzacja': 'AC',
    'klimatyzację': 'AC',
    'ogródek': 'garden',
    'ogród': 'garden',
    'ogrodem': 'garden',
    'pom. użytkowe': 'utility_room',
    'pomieszczenie użytkowe': 'utility_room',
    'garaż/miejsce parkingowe': 'parking_space',
    'garaż': 'parking_space',
    'miejsce parkingowe': 'parking_space',
    'taras': 'terrace',
    'balkon': 'balcony',
    'tylko dla niepalących': 'non_smokers_only',
    'Tylko osoby niepalące': 'non_smokers_only',
    'dla osób niepalących': 'non_smokers_only',
    'oddzielna kuchnia': 'separate_kitchen',
    'piwnica': 'basement',
    'piwnicą': 'basement',
    'piwnicę': 'basement',
    'wirtualny spacer': 'virtual_walk',
    'dwupoziomowe': 'two_level_apartment'
}