otodom_offer_data = {
    'Czynsz - dodatkowo': 'additional_rent',
    'Kaucja': 'security_deposit',
    'Rodzaj zabudowy': 'type_of_building',
    'Materiał budynku': 'building_material',
    'Okna': 'windows',
    'Ogrzewanie': 'heating',
    'Rok budowy': 'building_year',
    'Stan wykończenia': 'fit_out',
    'Dostępne od': 'ready_from',
    'Czynsz': 'additional_rent',
    'Forma własności': 'type_of_ownership',
    'Wynajmę również studentom': 'rental_for_students',
    'Rynek': 'type_of_market',
    'Wyposażenie': 'media',
    'Zabezpieczenia': 'security_measures',
    'Media': 'additonal_equipment',
    'Informacje dodatkowe': 'additional_information',
    'Powierzchnia': 'area',
    'Liczba pokoi': 'amount_of_rooms',
    'Piętro': 'apartment_level',
    'Liczba pięter': 'apartment_level',
}

offer_features = {
    'internet': 'internet',
    'telewizja kablowa': 'cable_tv',
    'teren zamknięty': 'closed_terrain',
    'monitoring / ochrona': 'monitoring_or_security',
    'monitoring': 'monitoring_or_security',
    'ochrona': 'monitoring_or_security',
    'osiedle strzeżone': 'monitoring_or_security',
    'domofon / wideofon': 'entry_phone',
    'domofon': 'entry_phone',
    'wideofon': 'entry_phone',
    'drzwi / okna antywłamaniowe': 'antibulglar_doors_windows',
    'drzwi antywłamaniowe': 'antibulglar_doors_windows',
    'okna antywłamaniowe': 'antibulglar_doors_windows',
    'system alarmowy': 'alarm_system',
    'alarm': 'alarm_system',
    'rolety antywłamaniowe': 'antibulglar_blinds',
    'zmywarka': 'dishwasher',
    'zmywarkę': 'dishwasher',
    'zmywarką': 'dishwasher',
    'kuchenka': 'cooker',
    'kuchenkę': 'cooker',
    'kuchenką': 'cooker',
    'lodówka': 'fridge',
    'lodówkę': 'fridge',
    'lodówką': 'fridge',
    'zamrażarkę': 'fridge',
    'zamrażarką': 'fridge',
    'piekarnik': 'oven',
    'pralka': 'washing_machine',
    'pralkę': 'washing_machine',
    'pralką': 'washing_machine',
    'telewizor': 'tv',
    'telewizj': 'tv',
    'winda': 'elevator',
    'windę': 'elevator',
    'windą': 'elevator',
    'telefon': 'phone',
    'klimatyzacja': 'AC',
    'klimatyzację': 'AC',
    'ogródek': 'garden',
    'ogród': 'garden',
    'ogrodem': 'garden',
    'pom. użytkowe': 'utility_room',
    'pomieszczenie użytkowe': 'utility_room',
    'garaż/miejsce parkingowe': 'parking_space',
    'garaż': 'parking_space',
    'miejsce parkingowe': 'parking_space',
    'taras': 'terrace',
    'balkon': 'balcony',
    'tylko dla niepalących': 'non_smokers_only',
    'Tylko osoby niepalące': 'non_smokers_only',
    'dla osób niepalących': 'non_smokers_only',
    'oddzielna kuchnia': 'separate_kitchen',
    'piwnica': 'basement',
    'piwnicą': 'basement',
    'piwnicę': 'basement',
    'wirtualny spacer': 'virtual_walk',
    'dwupoziomowe': 'two_level_apartment'
}